### ISSUE TITLE
Lake Formation Lab - no table created after blueprint workflow completed

### ISSUE THREAD

**Issue by pinkuchi** [aws-samples/data-engineering-for-aws-immersion-day#25]
Shows completed with no error for workflow. But there is no table created by the workflow.

Might because of the same error as Data Validation and ETL:
Cannot Save the Glue jobs because cannot find the path to store scripts, history in S3.  it would not create new folders

**Comment by melodyyangaws** [comment]
yes, you are on the right track. Glue job can't automatically create the script S3 bucket due to a recent bug discovered in Glue. The bug has been taken care of and will be fixed in the next couple of weeks. For the time being, please manually create a new S3 bucket storing the scripts in glue. It should enable you go ahead with the rest of labs.

**Comment by melodyyangaws** [comment]
the bug is fixed in June
